// Prints the contents of `cerb_types.h`: definitions of the Cerberus
// implementation-defined types and constants, matching the toolchain that
// builds the runtime. The `__cerbty_*`/`__cerbvar_*` names come from
// Cerberus's libc headers and survive in the pre-processed sources that
// Fulminate instruments, so they must agree with the host ABI.
#include <assert.h>
#include <limits.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

// The name of the standard integer type that `T` aliases, or NULL if none.
#define TYPE_NAME(T)                                                                     \
  _Generic((T)0,                                                                         \
      char: "char",                                                                      \
      signed char: "signed char",                                                        \
      unsigned char: "unsigned char",                                                    \
      short: "short",                                                                    \
      unsigned short: "unsigned short",                                                  \
      int: "int",                                                                        \
      unsigned int: "unsigned int",                                                      \
      long: "long",                                                                      \
      unsigned long: "unsigned long",                                                    \
      long long: "long long",                                                            \
      unsigned long long: "unsigned long long",                                          \
      default: NULL)

static void print_typedef(const char* name, const char* def) {
  assert(def != NULL);
  printf("typedef %s __cerbty_%s;\n", def, name);
}

// The integer constant suffix giving a literal the unsigned type named `def`.
static const char* unsigned_suffix(const char* def) {
  assert(def != NULL);
  if (strcmp(def, "unsigned int") == 0) {
    return "U";
  }
  if (strcmp(def, "unsigned long") == 0) {
    return "UL";
  }
  if (strcmp(def, "unsigned long long") == 0) {
    return "ULL";
  }
  assert(false);
  return NULL;
}

int main(void) {
  printf("// System dependent definitions of the basic Cerberus types.\n");
  printf("// Generated by gen_cerb_types.c during the build. DO NOT EDIT.\n");
  printf("#ifndef CERB_TYPES\n");
  printf("#define CERB_TYPES\n");
  printf("\n");
  print_typedef("uint8_t", TYPE_NAME(uint8_t));
  print_typedef("uint16_t", TYPE_NAME(uint16_t));
  print_typedef("uint32_t", TYPE_NAME(uint32_t));
  print_typedef("uint64_t", TYPE_NAME(uint64_t));
  printf("\n");
  print_typedef("int8_t", TYPE_NAME(int8_t));
  print_typedef("int16_t", TYPE_NAME(int16_t));
  print_typedef("int32_t", TYPE_NAME(int32_t));
  print_typedef("int64_t", TYPE_NAME(int64_t));
  printf("\n");
  print_typedef("intmax_t", TYPE_NAME(intmax_t));
  print_typedef("uintmax_t", TYPE_NAME(uintmax_t));
  printf("\n");
  print_typedef("uintptr_t", TYPE_NAME(uintptr_t));
  print_typedef("intptr_t", TYPE_NAME(intptr_t));
  print_typedef("ptrdiff_t", TYPE_NAME(ptrdiff_t));
  print_typedef("size_t", TYPE_NAME(size_t));
  print_typedef("wchar_t", TYPE_NAME(wchar_t));
  printf("\n");
  printf("#define __cerbvar_%-13s %zu\n", "MAX_ALIGNMENT", _Alignof(max_align_t));
  printf("#define __cerbvar_%-13s 0\n", "NULL");
  printf("#define __cerbvar_%-13s %d\n", "INT_MAX", INT_MAX);
  assert(INT_MIN + INT_MAX == -1);
  printf("#define __cerbvar_%-13s (-%d - 1)\n", "INT_MIN", INT_MAX);
  printf("#define __cerbvar_%-13s %ju%s\n",
      "SIZE_MAX",
      (uintmax_t)SIZE_MAX,
      unsigned_suffix(TYPE_NAME(size_t)));
  printf("\n");
  printf("#endif\n");
  return 0;
}
