/**
 * @file transform_template.h
 * @brief Shared vocabulary and parameter contract for the cn_term transformer
 *        engine template (transform.inc.c).
 *
 * The engine replaces the previously hand-duplicated per-domain walkers
 * (bennet_<dom>_transform_{forward,backward,backward_assume}) with a single
 * include-template. Each domain defines a set
 * of static basis functions over bennet_tagged_domain values and then
 * instantiates the engine with token-pasting parameters:
 *
 *   #define ABSINT_DOM congr                  symbol prefix (required)
 *   #include <bennet/internals/domains/transform.inc.c>
 *
 * Comparison refinements always push via collect-syms + one targeted
 * backward walk per symbol (Gauss-Seidel), and an unsatisfiable comparison
 * sets every symbol of both sides to bottom. (tnum's legacy SYM-only
 * application and missing unsat protocol - defect D2 - were reproduced by
 * two further toggles during its mechanical port and removed again by its
 * precision commit.)
 *
 * Assume recurses through the logical structure for every domain: NOT flips
 * the polarity, AND-true / OR-false thread the two branch assumptions, and
 * AND-false / OR-true (formerly unhandled) take the pointwise
 * join of the two branch assumptions over the term's symbols via the
 * per-domain tagged join.
 *
 * The engine is deliberately a *parity* engine: it reproduces the exact
 * traversal, gating, and application order of the legacy walkers (verified
 * by test/bennet/absint_difftest.cpp), including their precision limits.
 * The HC4-style single-walk backward pass with deposit-at-every-SYM from
 * the OCaml reference (nonRelational.ml) is deferred to P6, as is caching
 * across the assume/backward boundary and arena allocation of tree nodes.
 *
 * Basis contract (all static, defined before the #include; <dom> = the
 * ABSINT_DOM prefix; "tagged" = bennet_tagged_domain):
 *
 *   Forward transfer -- unsupported operations return top of the result
 *   type; a NULL state read yields top via bennet_absint_state_get_<dom>:
 *     tagged <dom>_basis_const(cn_term* t);
 *     tagged <dom>_basis_forward_unop(cn_unop op, tagged* v,
 *                                     cn_base_type* result_type);
 *     tagged <dom>_basis_forward_binop(cn_binop op, tagged* l, tagged* r,
 *                                      cn_base_type* result_type);
 *     tagged <dom>_basis_forward_cast(cn_base_type* to, tagged* v);
 *     tagged <dom>_basis_shift_forward(cn_term* t, tagged* base,
 *                                      tagged* index_or_null);
 *     tagged <dom>_basis_ite_join(tagged* then_v, tagged* else_v,
 *                                 cn_base_type* term_type);
 *
 *   Backward transfer -- BENNET_ABSINT_BW_STOP means "cannot invert, make
 *   no refinement" (the engine returns the state unchanged);
 *   BENNET_ABSINT_BW_DESCEND writes the value to push into the descended
 *   child through *down:
 *     bennet_absint_bw_action <dom>_basis_backward_unop(cn_unop op,
 *         tagged* out, tagged* operand_fwd, cn_base_type* operand_type,
 *         tagged* down);
 *     bennet_absint_bw_action <dom>_basis_backward_binop(cn_binop op,
 *         bool target_is_left, tagged* out, tagged* other_fwd,
 *         tagged* target_fwd, cn_base_type* target_type, tagged* down);
 *     bennet_absint_bw_action <dom>_basis_backward_cast(
 *         cn_base_type* src_type, cn_base_type* dst_type, tagged* out,
 *         tagged* down);
 *     bennet_absint_bw_action <dom>_basis_shift_backward(cn_term* t,
 *         bool target_is_base, tagged* out, tagged* sibling_fwd,
 *         tagged* target_fwd, tagged* down);
 *   (operand_fwd / target_fwd are the cached forward values of the child
 *   being descended into -- tnum meets its bitwise refinements with them;
 *   congr and wint ignore them.)
 *
 *   Comparison refinement for assume -- fills *l_ref / *r_ref (tagged with
 *   the caller-supplied ref types, which carry the pointer-comparison
 *   retagging quirk) and reports which sides to push back down. A domain
 *   with no rule for the operator/polarity returns has_rule = false and the
 *   engine makes no refinement at all (matching the legacy copy paths).
 *   Unsatisfiability is signaled by writing bottom into a refined slot:
 *     bennet_absint_cmp_result <dom>_basis_assume_cmp(cn_binop op,
 *         bool value, tagged* l_fwd, tagged* r_fwd,
 *         cn_base_type* l_ref_type, cn_base_type* r_ref_type,
 *         tagged* l_ref, tagged* r_ref);
 *
 * The engine additionally calls these existing extern per-domain operations
 * (generated by absint.h macros / defined in the domain .c):
 *   bennet_tagged_domain_{is_bottom,top,bottom,join,copy}_<dom>
 *   bennet_absint_state_{get,set,meet,copy,is_bottom}_<dom>
 */
#ifndef BENNET_TRANSFORM_TEMPLATE_H
#define BENNET_TRANSFORM_TEMPLATE_H

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Result of a per-operation backward transfer. */
typedef enum {
  BENNET_ABSINT_BW_STOP,   /* no sound inversion; leave the state unchanged */
  BENNET_ABSINT_BW_DESCEND /* recurse into the target child with *down */
} bennet_absint_bw_action;

/* Result of a comparison refinement (assume). apply_left/apply_right let a
 * domain skip pushing one side (wint skips top refinements; congr pushes
 * unconditionally -- both legacy behaviors). Ignored when has_rule is
 * false. */
typedef struct {
  bool has_rule;
  bool apply_left;
  bool apply_right;
} bennet_absint_cmp_result;

/* The assume-side local-iteration fuel is a runtime knob:
 * bennet_{set,get}_dynamic_local_iterations in bennet/internals/absint.h,
 * driven by the `--dynamic-local-iterations` flag (default 1, single-pass;
 * this deliberately diverges from the OCaml engine's
 * TestGenConfig.get_local_iterations() = 10). */

#ifdef __cplusplus
}
#endif

#endif /* BENNET_TRANSFORM_TEMPLATE_H */
